### PR TITLE
r0.6

### PR DESCRIPTION
**Pull request by mossmann**
- rename USB ports
- support passthrough power up to 20 V
- add voltage and current monitoring
- add Type-C controller to AUX and TARGET ports
- add USER button connected to FPGA
- move Pmod connectors to same edge of board
- add mezzanine connector
- increase PCB size to 56x56 mm
- add mounting holes

### CODE REVIEW

**Review by yhetti — COMMENTED** [review]
Everything seems to be there except for two files.:
       /libraries/usb.bck (basically empty file, but my be needed to be backwards compatible with KiCAD5 and earlier?)
       /libraries/luna.pretty/D_SOD-123FL.kicad_mod (you seem to have found a library footprint to replace this?)

The only other thing I see is that the aux_port.kicad_sch sheet opens a little wonky: 
image

**Comment by mossmann** [comment]
> /libraries/usb.bck (basically empty file, but my be needed to be backwards compatible with KiCAD5 and earlier?)

I believe this is a backup file. It is ignored in .gitignore, so it shouldn't be committed. Did KiCad complain about it being missing?

**Comment by mossmann** [comment]
The AUX port sheet content going outside the boundary is a cosmetic issue that gets cleaned up in a later revision.

**Comment by mossmann** [comment]
D_SOD-123FL.kicad_mod is not needed until it is introduced in r0.7

**Pull request merged**
